### ISSUE TITLE
ObjectId generation

### ISSUE THREAD

**Issue by stephenmuss** [checkiz/elixir-bson#9]
It would be nice if there were a way to generate new ObjectIds.

**Comment by jerp** [comment]
use `Mongo.Server.assign_id/2` or its alias `Mongo.assign_id/2`

   [%{a: -23}, %{a: -24, b: 1}] |> Mongo.Server.assign_id(ctx[:mongo])

see mongo_crud_test.exs

**Comment by stephenmuss** [comment]
The problem with that approach is that I would need to add Mongo as an extra dependency. It would be nice to be able to do this with just the bson library.
